version: 0.2

phases:
  install:
    commands:
      - echo "Checking Node and npm versions"
      - node -v
      - npm -v

  pre_build:
    commands:
      - echo "Installing frontend dependencies"
      - cd frontend
      - npm install
      - cd ..

      - echo "Installing backend dependencies"
      - cd backend
      - npm install --include=dev
      - npm ls typescript
      - cd ..

  build:
    commands:
      - echo "Running frontend tests"
      - cd frontend
      - CI=true npm test -- --watchAll=false
      - npm run build
      - cd ..

      - echo "Building backend"
      - cd backend
      - npm run build
      - cd ..

artifacts:
  files:
    - '**/*'